# This is a basic workflow to help you get started with Actions

name: fastfrog checkin

# Controls when the workflow will run
on:
  # 定时任务北京时间每天11点
  schedule:
    - cron: "0 3 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  main:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out to master
      - name: Checkout
        uses: actions/checkout@master

      # nodejs install
      - name: nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 16

      # npm install
      - name: npm
        run: |
          npm install
        env:
          CI: true

      # Run
      - name: Run
        run: |
          FASTFROG_TOKEN='${{ secrets.FASTFROG_TOKEN }}' FEISHUBOT_WEBHOOK='${{ secrets.FEISHUBOT_WEBHOOK }}' FEISHUBOT_SECRET='${{ secrets.FEISHUBOT_SECRET }}' npm start fastfrog
        env:
          CI: true
